### ISSUE TITLE
Font Files are Broken

### ISSUE THREAD

**Issue by ithinkandicode** [Etcetera-Type-Co/Anybody#6]
The fonts available by downloading from [Releases](https://github.com/Etcetera-Type-Co/Anybody/releases), or from [Google Fonts](https://fonts.google.com/specimen/Anybody), are broken.

The versions available in the [old](https://github.com/Etcetera-Type-Co/Anybody/tree/master/old/static/ttf) folder work correctly though. And the woff files served by Google Fonts work too (just not the downloaded versions).

Here's the Windows font preview for the files from the latest release, the same applies to the versions downloaded from Google Fonts:

![image](https://user-images.githubusercontent.com/43499897/220728595-0faef396-e68f-4590-bdc1-fa02f655c989.png)

**Comment by sursly** [comment]
Ooof, not good. This is the first I'm hearing about this, which is surprising since the font has been out for a couple years without any reported issues. I'd love to know if someone else can replicate it.

**Comment by ithinkandicode** [comment]
I've asked some guys on Discord to test and confirm issues. Here's what we've found:

- For the [Google Fonts](https://fonts.google.com/specimen/Anybody) version, all the fonts are broken.
- For the [GitHub](https://github.com/Etcetera-Type-Co/Anybody/releases/tag/v1.111) version:
    - The **static** fonts are working correctly 👍
    - The **variable** fonts are broken

**Comment by sursly** [comment]
Thanks @ithinkandicode - this is very weird. I'll take a look at it, maybe @RosaWagner can also find some workaround. Thanks for bringing this up!

**Comment by RosaWagner** [comment]
I would like to re-build the font to debug the problem but I am having issues with the open corners and the quadratic curves in the sources. I have interpolation error to have open corner interpolating in normal segment within the same glyphs. Honnestly, seeing the mix of quadradic and cubic curves in the sources, I am surprised we were able to build it at all ^^

@sursly can you look into: 'N', 'V', 'V.ss01', 'W', 'Y', 'a', 'f', 'four', 'four.dnom', 'lira', 'quotedblright', 'quoteleft', 'quoteright', 'seven', 'seven.dnom', 'sterling', 'v', 'w', 'y', 'z'. First I gonna make you a PR cause I changed the axis name again to see if the problem would come from 'ital' instead of 'slant'.

**Comment by sursly** [comment]
Thanks @RosaWagner, merged! Going to take a look at the changes.

**Comment by sursly** [comment]
Ok @RosaWagner, fixed those open corners for you! Let me know what else has to happen, thanks again!

**Comment by RosaWagner** [comment]
thanks @sursly the slicing between Roman and Italic with slant axis revealed still more building bugs that I need to address to the tool people. It looks like we should update the font quickly so I may have separate the sources, are you okay with that?

**Comment by sursly** [comment]
Go for it @RosaWagner ! I swear we ready separated them, but clearly not.
